server:
  port: 8700
spring:
  application:
    name: nativeconfigserver
  profiles:
    active: native
    #本地配置
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared