server:
  port: 8500
spring:
  application:
    name: feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
